# Generated by Django 2.1.5 on 2019-10-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skladik', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sklad_item',
            name='category',
        ),
        migrations.DeleteModel(
            name='categorya',
        ),
        migrations.DeleteModel(
            name='sklad_item',
        ),
    ]
