# Generated by Django 2.1.5 on 2019-10-11 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skladik', '0002_auto_20191011_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_sotrudnika', models.IntegerField()),
                ('sotrudnik_name', models.CharField(max_length=200)),
                ('sotrudnik_lastname', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('adres', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='postavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_postavki', models.IntegerField()),
                ('postavshik_name', models.CharField(max_length=200)),
                ('adres', models.CharField(max_length=200)),
                ('telephone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sklad_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('col_vo_sklad', models.IntegerField()),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skladik.categorya')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skladik.employee')),
                ('postavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skladik.postavka')),
            ],
        ),
    ]
