# Generated by Django 2.1.5 on 2019-10-15 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skladik', '0003_categorya_employee_postavka_sklad_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='otpravka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_vo_item', models.IntegerField()),
                ('mesto_pribitiya', models.CharField(max_length=200)),
                ('zakazchik_name', models.CharField(max_length=200)),
                ('otpravka_date', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skladik.sklad_item')),
            ],
        ),
    ]
