# Generated by Django 2.1.5 on 2019-10-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skladik', '0004_otpravka'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad_item',
            name='cover',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
