# Generated by Django 2.1.5 on 2019-10-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skladik', '0005_sklad_item_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sklad_item',
            name='cover',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
    ]
