# Generated by Django 2.1.5 on 2019-10-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skladik', '0006_auto_20191024_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sklad_item',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
