# Generated by Django 2.1.5 on 2019-10-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skladik', '0007_auto_20191024_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sklad_item',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
